#ifndef AFENGINE_FOUNDATION_RUNTIME_INTERNAL_MACOS_COCOA_AFENGINEAPPLICATION_H
#define AFENGINE_FOUNDATION_RUNTIME_INTERNAL_MACOS_COCOA_AFENGINEAPPLICATION_H

#ifdef __OBJC__
  #include <AppKit/AppKit.h>

@interface AFEngineApplication : NSApplication
@end

#endif

#endif  // AFENGINE_FOUNDATION_RUNTIME_INTERNAL_MACOS_COCOA_AFENGINEAPPLICATION_H
