#ifndef AFENGINE_RUNTIME_PLATFORM_MACOS_AFENGINEWINDOW_H
#define AFENGINE_RUNTIME_PLATFORM_MACOS_AFENGINEWINDOW_H

class AFEngineWindow {};

#endif  // AFENGINE_RUNTIME_PLATFORM_MACOS_AFENGINEWINDOW_H
